# Full Example: https://github.com/geekan/MetaGPT/blob/main/config/config2.example.yaml
# Reflected Code: https://github.com/geekan/MetaGPT/blob/main/metagpt/config2.py
# Config Docs: https://docs.deepwisdom.ai/main/en/guide/get_started/configuration.html
llm:
  api_type: "zhipuai"  # or azure / ollama / groq etc.
  model: "GLM-4"  # or gpt-3.5-turbo
  base_url: "https://open.bigmodel.cn/api/paas/v4/async/chat/completions"  # or forward url / other llm url
  api_key: "365603af9eae7ce8575825d75a479e62.tsOfgva2HWoeKpL1"